#include "arduino_secrets.h"
// hp_BH1750 - Version: Latest 
#include <hp_BH1750.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/9792ee4a-a0f6-4a36-a47c-302eb16327e7 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float intensity;
  bool sunlighttrack;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/


#include "thingProperties.h"

float sensor;
hp_BH1750 BH1750;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

pinMode(LED_BUILTIN, OUTPUT);

bool avail = BH1750.begin(BH1750_TO_GROUND);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  BH1750.start();
  sensor = BH1750.getLux();
  intensity = sensor;
  
  
}


/*
  Since Intensity is READ_WRITE variable, onIntensityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onIntensityChange()  {
  // Add your code here to act upon Intensity change
  if(intensity > 300)
  {
    sunlighttrack=true;
    onSunlighttrackChange();
    
    Serial.print("light intensity: ");
    Serial.print(intensity);
    Serial.println("suffiecient sunlight present! ");
    
  }
  
  else
  {
    
    sunlighttrack = false;
    onSunlighttrackChange();
    
    digitalWrite(LED_BUILTIN, HIGH);
    Serial.print("light intensity: ");
    Serial.print(intensity);
    Serial.println(" insufficient sunlight ");
    
  }
  
  delay(5000);
  
  
}

/*
  Since Sunlighttrack is READ_WRITE variable, onSunlighttrackChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSunlighttrackChange()  {
  // Add your code here to act upon Sunlighttrack change
  
  if(sunlighttrack = true)
  {
    
    digitalWrite(LED_BUILTIN, HIGH);
    
    delay(2000);
    
  }
  
  else if(sunlighttrack = false)
  {
    
    digitalWrite(LED_BUILTIN, LOW);
    
    delay(2000);
    
  }
}
